apiVersion: v1
kind: Service
metadata:
  name: checkpoint-mohamad-service
spec:
  selector:
    app: checkpoint-mohamad
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
