name: Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'microservice1/**'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubectl
        uses: eks-actions/eks-kubectl-action@v2
        with:
          cluster-name: ${{ env.EKS_CLUSTER_NAME }}
          region: ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc checkpoint-mohamad-service
